include:
  - project: perun/common
    file: /templates/.gitlab-ci-template.yml

e2e_tests:
  variables:
    GUI_COMMIT_HASH: ${CI_COMMIT_SHA}
  trigger:
    project: perun/perun-idm/e2e-perun
    strategy: depend

