language: node_js
node_js:
  - "16.20.2"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - nx affected:lint
  - nx affected:build --prod
