services:
  db:
    build: ./e2e/docker-postgresql/.
    environment:
      POSTGRESQL_USERNAME: perun
      POSTGRESQL_PASSWORD: test
      POSTGRESQL_DATABASE: perun
      # renovate: datasource=gitlab-packages depName=perun/perun-idm/perun:release versioning=semver registryUrl=https://gitlab.ics.muni.cz
      RPC_VERSION: "34.3.0"
    networks:
      - e2e-net
  perun-rpc:
    build: ./e2e/docker-rpc/.
    depends_on:
      - db
    networks:
      - e2e-net
    hostname: perun-rpc
  perun-apache:
    image: registry.gitlab.ics.muni.cz:443/perun/ci/pipeline-components/perun-apache:latest
    depends_on:
      - perun-rpc
    ports:
      - "8080:8080"
    hostname: perun-api
    networks:
      - e2e-net

networks:
  e2e-net:
