/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Attribute } from './attribute';
import { UserExtSource } from './userExtSource';

/**
 * input to addUserExtSourceWithAttributes
 */
export interface AddUserExtSourceWithAttributesInput {
  user: number;
  userExtSource: UserExtSource;
  attributes: Array<Attribute>;
}
