/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const ApplicationsOrderColumn = {
  ID: 'ID',
  DATE_CREATED: 'DATE_CREATED',
  TYPE: 'TYPE',
  STATE: 'STATE',
  SUBMITTER: 'SUBMITTER',
  GROUP_NAME: 'GROUP_NAME',
  MODIFIED_BY: 'MODIFIED_BY',
} as const;
export type ApplicationsOrderColumn =
  (typeof ApplicationsOrderColumn)[keyof typeof ApplicationsOrderColumn];
