/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RichMember } from './richMember';
import { GroupResourceStatus } from './groupResourceStatus';

/**
 * represents a member of a group assigned to a resource
 */
export interface AssignedMember {
  richMember?: RichMember;
  status?: GroupResourceStatus;
}
export namespace AssignedMember {}
