/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeDefinition } from './attributeDefinition';

export interface Attribute extends AttributeDefinition {
  valueCreatedAt?: string | null;
  valueCreatedBy?: string | null;
  valueModifiedAt?: string | null;
  valueModifiedBy?: string | null;
  value?: any | null;
}
