/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const BlockedLoginsOrderColumn = {
  LOGIN: 'LOGIN',
  NAMESPACE: 'NAMESPACE',
} as const;
export type BlockedLoginsOrderColumn =
  (typeof BlockedLoginsOrderColumn)[keyof typeof BlockedLoginsOrderColumn];
