/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CantBeApprovedException {
  errorId?: string;
  name?: string;
  message?: string;
  affiliation?: string | null;
  applicationId?: number;
  category?: string | null;
  reason?: string | null;
  soft?: boolean;
}
