/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * type of destination, i.e. way of delivery of service settings
 */
export const DestinationType = {
  host: 'host',
  url: 'url',
  userhost: 'user@host',
  userhost_port: 'user@host:port',
  service_specific: 'service-specific',
  userhost_windows: 'user@host-windows',
  host_windows_proxy: 'host-windows-proxy',
  s3: 's3',
  s3_json: 's3-json',
  url_json: 'url-json',
} as const;
export type DestinationType = (typeof DestinationType)[keyof typeof DestinationType];
