/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BanOnFacility } from './banOnFacility';
import { RichUser } from './richUser';
import { Facility } from './facility';

export interface EnrichedBanOnFacility {
  facility?: Facility;
  user?: RichUser;
  ban?: BanOnFacility;
}
