/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExtSource } from './extSource';

export interface EnrichedExtSource {
  extSource?: ExtSource;
  attributes?: { [key: string]: string };
}
