/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrichedExtSource } from './enrichedExtSource';

export interface EnrichedIdentity {
  id?: number;
  name?: string;
  organization?: string;
  email?: string;
  identities?: Array<EnrichedExtSource>;
}
