/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * currently supported formats are DOT and TGF
 */
export const GraphFileFormat = {
  DOT: 'DOT',
  TGF: 'TGF',
} as const;
export type GraphFileFormat = (typeof GraphFileFormat)[keyof typeof GraphFileFormat];
