/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Auditable } from './auditable';

export interface Group extends Auditable {
  name?: string;
  shortName?: string;
  description?: string | null;
  voId?: number;
  parentGroupId?: number | null;
  uuid?: string;
}
