/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * status of the group-resource assignment
 */
export const GroupResourceStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  FAILED: 'FAILED',
  PROCESSING: 'PROCESSING',
} as const;
export type GroupResourceStatus = (typeof GroupResourceStatus)[keyof typeof GroupResourceStatus];
