/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * admin roles for a group
 */
export const GroupAdminRoles = {
  GROUPOBSERVER: 'GROUPOBSERVER',
  GROUPMEMBERSHIPMANAGER: 'GROUPMEMBERSHIPMANAGER',
  GROUPADMIN: 'GROUPADMIN',
  GROUPCREATOR: 'GROUPCREATOR',
} as const;
export type GroupAdminRoles = (typeof GroupAdminRoles)[keyof typeof GroupAdminRoles];
