/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Attribute } from './attribute';
import { GenDataNode } from './genDataNode';

export interface HashedGenData {
  attributes?: { [key: string]: Array<Attribute> };
  hierarchy?: { [key: string]: GenDataNode };
}
