/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemberCandidate } from './memberCandidate';

/**
 * input to invite member candidates
 */
export interface InputInviteMemberCandidates {
  vo: number;
  candidates: Array<MemberCandidate>;
  lang: string;
  group?: number;
}
