/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvitationsPageQuery } from './invitationsPageQuery';

/**
 * input to getInvitationsPage
 */
export interface InputGetInvitationsPage {
  group: number;
  query: InvitationsPageQuery;
}
