/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupsPageQuery } from './groupsPageQuery';

/**
 * input to getSubgroupsPage
 */
export interface InputGetPaginatedSubgroups {
  group: number;
  attrNames: Array<string>;
  query: GroupsPageQuery;
}
