/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * input to checkHtmlInput
 */
export interface InputCheckHtmlInput {
  /**
   * input html to check
   */
  html: string;
}
