/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Input to getMembersByUserAttributes
 */
export interface InputGetMembersByUserAttributes {
  /**
   * vo id
   */
  vo: number;
  /**
   * Map of attribute names with searching values Map<string,string>
   */
  userAttributesWithSearchingValues: { [key: string]: string };
}
