/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MailType } from './mailType';

/**
 * input to sendMessageNewRegistrar
 */
export interface InputSendMessageNewRegistrar {
  mailType: MailType;
  /**
   * group id
   */
  group?: number;
  /**
   * vo id
   */
  vo?: number;
  /**
   * user id
   */
  user?: number;
  /**
   * issuer of the user\'s identity
   */
  issuer: string;
  /**
   * identifier of the user
   */
  identifier: string;
  /**
   * application id in new Registrar
   */
  newRegAppId?: string;
  /**
   * type of the application from new Registrar
   */
  newRegAppType?: InputSendMessageNewRegistrar.NewRegAppTypeEnum;
  /**
   * you can specify reason for case: mailType == APP_REJECTED_USER
   */
  reason?: string;
  /**
   * Map of the email items, {formItemDataUUID}->{value}
   */
  emailItems?: { [key: string]: string };
  /**
   * Map of the item data, itemShortname->itemData
   */
  itemsByShortname?: { [key: string]: string };
  /**
   * Map of the items with a destination attribute, destinationAttribute->itemData
   */
  destinationValues?: { [key: string]: string };
}
export namespace InputSendMessageNewRegistrar {
  export const NewRegAppTypeEnum = {
    INITIAL: 'INITIAL',
    EXTENSION: 'EXTENSION',
  } as const;
  export type NewRegAppTypeEnum = (typeof NewRegAppTypeEnum)[keyof typeof NewRegAppTypeEnum];
}
