/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * input for reservePasswordForLogin
 */
export interface InputReservePasswordForLogin {
  login: string;
  namespace: string;
  password: string;
}
