/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Input to getResources
 */
export interface InputGetMatchResources {
  /**
   * True if partial match is allowed
   */
  allowPartialMatchForString: boolean;
  /**
   * Map of attribute names with searching values Map<sting,string>
   */
  attributesWithSearchingValues: { [key: string]: string };
}
