/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * input for changePasswordForLogin
 */
export interface InputChangePasswordForLogin {
  login: string;
  namespace: string;
  newPassword: string;
  oldPassword?: string;
  /**
   * True if the oldPassword has to be checked. When omitted it defaults to false.
   */
  checkOldPassword?: boolean;
}
