/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DestinationPropagationType } from './destinationPropagationType';
import { Service } from './service';
import { DestinationType } from './destinationType';

/**
 * input to addDestinationToMultipleServices
 */
export interface InputAddDestinationToMultipleServices {
  services: Array<Service>;
  facility: number;
  destination: string;
  type: DestinationType;
  propagationType?: DestinationPropagationType;
}
export namespace InputAddDestinationToMultipleServices {}
