/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * input for reservePasswordForUser
 */
export interface InputReservePasswordForUser {
  user: number;
  namespace: string;
  password: string;
}
