/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * input to deleteGroup
 */
export interface InputDeleteGroups {
  groups: Array<number>;
  /**
   * boolean for force delete
   */
  forceDelete: boolean;
}
