/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BanOnVo } from './banOnVo';

/**
 * input to updateBan
 */
export interface InputUpdateBan1 {
  banOnVo: BanOnVo;
}
