/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RichDestination } from './richDestination';

/**
 * input to blockServicesOnDestinations
 */
export interface InputBlockServicesOnDestinations {
  richDestinations: Array<RichDestination>;
}
