/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvitationStatus } from './invitationStatus';
import { Invitation } from './invitation';

export interface InvitationWithSender extends Invitation {
  senderName?: string;
  senderEmail?: string;
}
export namespace InvitationWithSender {}
