/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const InvitationsOrderColumn = {
  ID: 'ID',
  STATUS: 'STATUS',
  EXPIRATION: 'EXPIRATION',
  RECEIVER_NAME: 'RECEIVER_NAME',
  RECEIVER_EMAIL: 'RECEIVER_EMAIL',
  SENDER_NAME: 'SENDER_NAME',
} as const;
export type InvitationsOrderColumn =
  (typeof InvitationsOrderColumn)[keyof typeof InvitationsOrderColumn];
