/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Auditable } from './auditable';
import { InvitationStatus } from './invitationStatus';

export interface Invitation extends Auditable {
  voId?: number;
  groupId?: number;
  applicationId?: number | null;
  senderId?: number;
  receiverName?: string;
  receiverEmail?: string;
  redirectUrl?: string | null;
  token?: string | null;
  language?: string;
  expiration?: string;
  status?: InvitationStatus;
}
