/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * statuses of a member in a group
 */
export const MemberGroupStatus = {
  VALID: 'VALID',
  EXPIRED: 'EXPIRED',
} as const;
export type MemberGroupStatus = (typeof MemberGroupStatus)[keyof typeof MemberGroupStatus];
