/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Auditable } from './auditable';
import { OwnerType } from './ownerType';

export interface Owner extends Auditable {
  name?: string;
  contact?: string;
  type?: OwnerType;
}
export namespace Owner {}
