/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * enumeration of types of Owners
 */
export const OwnerType = {
  technical: 'technical',
  administrative: 'administrative',
} as const;
export type OwnerType = (typeof OwnerType)[keyof typeof OwnerType];
