/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvitationWithSender } from './invitationWithSender';

export interface PaginatedInvitationsWithSender {
  offset: number;
  pageSize: number;
  totalCount: number;
  data: Array<InvitationWithSender>;
}
