/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * represents personal data change config
 */
export interface PersonalDataChangeConfig {
  enableLinkedName: boolean;
  enableCustomName: boolean;
  customNameRequiresApprove: boolean;
  enableLinkedOrganization: boolean;
  enableCustomOrganization: boolean;
  customOrganizationRequiresApprove: boolean;
  enableLinkedEmail: boolean;
  enableCustomEmail: boolean;
  customEmailRequiresVerification: boolean;
}
