/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Localized freemarker template
 */
export interface PerunNotifTemplateMessage {
  id?: number;
  templateId?: number;
  locale?: string;
  message?: string | null;
  subject?: string;
}
