/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * exception thrown from inside of Perun
 */
export interface PerunException {
  errorId?: string;
  name?: string;
  message?: string;
}
