/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerunNotifTemplateMessage } from './perunNotifTemplateMessage';
import { PerunNotifReceiver } from './perunNotifReceiver';
import { PerunNotifRegex } from './perunNotifRegex';

/**
 * Represents template for message sent to receivers
 */
export interface PerunNotifTemplate {
  id?: number;
  name?: string | null;
  matchingRegexs?: Array<PerunNotifRegex>;
  receivers?: Array<PerunNotifReceiver>;
  primaryProperties?: { [key: string]: Array<string> };
  notifyTrigger?: string;
  perunNotifTemplateMessages?: Array<PerunNotifTemplateMessage>;
  oldestMessageTime?: number | null;
  youngestMessageTime?: number | null;
  sender?: string | null;
  replyTo?: string | null;
}
