/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents objects, upon which Perun roles can be set, e.g. role RESOURCEADMIN can be set upon Resource, Vo, Facility or no object (None).
 */
export const RoleObject = {
  None: 'None',
  Group: 'Group',
  Vo: 'Vo',
  Facility: 'Facility',
  Resource: 'Resource',
  User: 'User',
  Member: 'Member',
} as const;
export type RoleObject = (typeof RoleObject)[keyof typeof RoleObject];
