/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RoleManagementRules {
  roleName: string;
  primaryObject: string | null;
  privilegedRolesToManage: Array<{ [key: string]: string | null }>;
  privilegedRolesToRead: Array<{ [key: string]: string | null }>;
  entitiesToManage: { [key: string]: string };
  assignedObjects: { [key: string]: string };
  assignableToAttributes: boolean;
  skipMFA: boolean;
  displayName: string;
}
