/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Auditable } from './auditable';

export interface Service extends Auditable {
  name?: string;
  description?: string;
  delay?: number;
  recurrence?: number;
  enabled?: boolean;
  script?: string;
  useExpiredMembers?: boolean;
  useExpiredVoMembers?: boolean;
  useBannedMembers?: boolean;
}
