/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const TaskResultStatus = {
  DONE: 'DONE',
  ERROR: 'ERROR',
  DENIED: 'DENIED',
  WARNING: 'WARNING',
} as const;
export type TaskResultStatus = (typeof TaskResultStatus)[keyof typeof TaskResultStatus];
