/**
 * Perun RPC API
 *
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerunBean } from './perunBean';

/**
 * input to unsetRoleWithUserComplementaryObject (supported objects: Group | RichGroup | Vo | Resource | Facility)
 */
export interface UnsetRoleWithUserComplementaryObject {
  role: string;
  /**
   * List of user ids
   */
  users: Array<number>;
  complementaryObject?: PerunBean;
}
