/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DTO representing action registry entry
 */
export interface AgeActionRecordDTO {
  /**
   * Identifying name of the action
   */
  actionName?: string;
  /**
   * Action description
   */
  actionDescription?: string;
}
