/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationDTO } from './applicationDTO';
import { ValidationError } from './validationError';

export interface ApplicationResultDTO {
  formSpecificationId?: string;
  application?: ApplicationDTO;
  errors?: Array<ValidationError>;
  error?: string;
}
