/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApprovalFailure } from './approvalFailure';
import { ApplicationDetailDTO } from './applicationDetailDTO';

export interface ApproveResultDTO {
  applicationDetail?: ApplicationDetailDTO;
  failures?: Array<ApprovalFailure>;
}
