/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DecisionDTO {
  id?: string;
  applicationId?: string;
  approverId?: string;
  approverName?: string;
  message?: string;
  timestamp?: string;
  type?: DecisionDTO.TypeEnum;
}
export namespace DecisionDTO {
  export const TypeEnum = {
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    CHANGES_REQUESTED: 'CHANGES_REQUESTED',
    FORCE_VERIFIED: 'FORCE_VERIFIED',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
