/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrichedFormItemDataDTO } from './enrichedFormItemDataDTO';
import { FormTypeConfig } from './formTypeConfig';

export interface EnrichedApplicationFormDTO {
  formSpecificationId: string;
  formItemData: Array<EnrichedFormItemDataDTO>;
  typeConfig: FormTypeConfig;
}
