/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ExtSource {
  name?: string;
  type?: ExtSource.TypeEnum;
}
export namespace ExtSource {
  export const TypeEnum = {
    X509: 'X509',
    IDP: 'IDP',
    KERBEROS: 'KERBEROS',
    SQL: 'SQL',
    ISMU: 'ISMU',
    LDAP: 'LDAP',
    PERUN: 'PERUN',
    INTERNAL: 'INTERNAL',
    XML: 'XML',
    CSV: 'CSV',
    GOOGLE: 'GOOGLE',
    EGISSO: 'EGISSO',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
