/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationDTO } from './applicationDTO';
import { EnrichedApplicationFormDTO } from './enrichedApplicationFormDTO';

export interface FormContextDTO {
  prefilledData?: EnrichedApplicationFormDTO;
  openApplications?: Array<ApplicationDTO>;
  oldRegUrl?: string;
}
