/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FormModuleDTO {
  name?: string;
  description?: string;
  requiredOptions?: Array<string>;
}
