/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FormTypeConfig {
  formType: FormTypeConfig.FormTypeEnum;
  attributeName?: string;
}
export namespace FormTypeConfig {
  export const FormTypeEnum = {
    INITIAL: 'INITIAL',
    EXTENSION: 'EXTENSION',
    CANCELLATION: 'CANCELLATION',
    UPDATE: 'UPDATE',
  } as const;
  export type FormTypeEnum = (typeof FormTypeEnum)[keyof typeof FormTypeEnum];
}
