/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormTransitionDTO } from './formTransitionDTO';
import { AssignedFormModuleDTO } from './assignedFormModuleDTO';

export interface FormSpecificationPatchRequest {
  autoFormTypes?: Array<FormSpecificationPatchRequest.AutoFormTypesEnum>;
  formTransitions?: Array<FormTransitionDTO>;
  formModules?: Array<AssignedFormModuleDTO>;
  namespace?: string;
}
export namespace FormSpecificationPatchRequest {
  export const AutoFormTypesEnum = {
    INITIAL: 'INITIAL',
    EXTENSION: 'EXTENSION',
    CANCELLATION: 'CANCELLATION',
    UPDATE: 'UPDATE',
  } as const;
  export type AutoFormTypesEnum = (typeof AutoFormTypesEnum)[keyof typeof AutoFormTypesEnum];
}
