/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExtSource } from './extSource';

export interface Identity {
  name?: string;
  organization?: string;
  email?: string;
  extSources?: Array<ExtSource>;
}
