/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IdmObject {
  idmObjectType: IdmObject.IdmObjectTypeEnum;
  objectId: string;
  name?: string;
}
export namespace IdmObject {
  export const IdmObjectTypeEnum = {
    VO: 'VO',
    GROUP: 'GROUP',
  } as const;
  export type IdmObjectTypeEnum = (typeof IdmObjectTypeEnum)[keyof typeof IdmObjectTypeEnum];
}
