/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemTexts } from './itemTexts';
import { ItemValidatorDTO } from './itemValidatorDTO';

export interface ItemDefinitionDTO {
  id?: string;
  formSpecificationId?: string;
  displayName: string;
  type: ItemDefinitionDTO.TypeEnum;
  updatable: boolean;
  required: boolean;
  defaultValue?: string;
  prefillStrategyIds?: Array<string>;
  destinationId?: string;
  formTypes: Array<ItemDefinitionDTO.FormTypesEnum>;
  texts: { [key: string]: ItemTexts };
  hidden: ItemDefinitionDTO.HiddenEnum;
  disabled: ItemDefinitionDTO.DisabledEnum;
  scope: ItemDefinitionDTO.ScopeEnum;
  validators?: Array<ItemValidatorDTO>;
}
export namespace ItemDefinitionDTO {
  export const TypeEnum = {
    HEADING: 'HEADING',
    SELECTION_CUSTOM: 'SELECTION_CUSTOM',
    SELECTIONBOX: 'SELECTIONBOX',
    CHECKBOX: 'CHECKBOX',
    SUBMIT_BUTTON: 'SUBMIT_BUTTON',
    DATE_PICKER: 'DATE_PICKER',
    LOGIN: 'LOGIN',
    PASSWORD: 'PASSWORD',
    VERIFIED_EMAIL: 'VERIFIED_EMAIL',
    HTML_COMMENT: 'HTML_COMMENT',
    TEXTFIELD: 'TEXTFIELD',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
  export const FormTypesEnum = {
    INITIAL: 'INITIAL',
    EXTENSION: 'EXTENSION',
    CANCELLATION: 'CANCELLATION',
    UPDATE: 'UPDATE',
  } as const;
  export type FormTypesEnum = (typeof FormTypesEnum)[keyof typeof FormTypesEnum];
  export const HiddenEnum = {
    NEVER: 'NEVER',
    ALWAYS: 'ALWAYS',
    IF_PREFILLED: 'IF_PREFILLED',
    IF_EMPTY: 'IF_EMPTY',
  } as const;
  export type HiddenEnum = (typeof HiddenEnum)[keyof typeof HiddenEnum];
  export const DisabledEnum = {
    NEVER: 'NEVER',
    ALWAYS: 'ALWAYS',
    IF_PREFILLED: 'IF_PREFILLED',
    IF_EMPTY: 'IF_EMPTY',
  } as const;
  export type DisabledEnum = (typeof DisabledEnum)[keyof typeof DisabledEnum];
  export const ScopeEnum = {
    GLOBAL: 'GLOBAL',
    GLOBAL_REQUIRED: 'GLOBAL_REQUIRED',
    FORM_SPECIFIC: 'FORM_SPECIFIC',
  } as const;
  export type ScopeEnum = (typeof ScopeEnum)[keyof typeof ScopeEnum];
}
