/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemTexts } from './itemTexts';
import { ItemValidatorDTO } from './itemValidatorDTO';

export interface ItemDefinitionPatchRequest {
  displayName?: string;
  updatable?: boolean;
  required?: boolean;
  defaultValue?: string;
  prefillStrategyIds?: Array<string>;
  destinationId?: string;
  formTypes?: Array<ItemDefinitionPatchRequest.FormTypesEnum>;
  texts?: { [key: string]: ItemTexts };
  hidden?: ItemDefinitionPatchRequest.HiddenEnum;
  disabled?: ItemDefinitionPatchRequest.DisabledEnum;
  validators?: Array<ItemValidatorDTO>;
}
export namespace ItemDefinitionPatchRequest {
  export const FormTypesEnum = {
    INITIAL: 'INITIAL',
    EXTENSION: 'EXTENSION',
    CANCELLATION: 'CANCELLATION',
    UPDATE: 'UPDATE',
  } as const;
  export type FormTypesEnum = (typeof FormTypesEnum)[keyof typeof FormTypesEnum];
  export const HiddenEnum = {
    NEVER: 'NEVER',
    ALWAYS: 'ALWAYS',
    IF_PREFILLED: 'IF_PREFILLED',
    IF_EMPTY: 'IF_EMPTY',
  } as const;
  export type HiddenEnum = (typeof HiddenEnum)[keyof typeof HiddenEnum];
  export const DisabledEnum = {
    NEVER: 'NEVER',
    ALWAYS: 'ALWAYS',
    IF_PREFILLED: 'IF_PREFILLED',
    IF_EMPTY: 'IF_EMPTY',
  } as const;
  export type DisabledEnum = (typeof DisabledEnum)[keyof typeof DisabledEnum];
}
