/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { EnrichedApplicationDTO } from './enrichedApplicationDTO';
import { SortObject } from './sortObject';

export interface PageEnrichedApplicationDTO {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: Array<EnrichedApplicationDTO>;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
