/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationResultDTO } from './applicationResultDTO';
import { SubmissionDTO } from './submissionDTO';

export interface SubmissionResultDTO {
  messages?: Array<string>;
  redirectUrl?: string;
  submission?: SubmissionDTO;
  applicationResults?: Array<ApplicationResultDTO>;
}
