/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationFormDTO } from './applicationFormDTO';

export interface SubmittedDataDTO {
  filledData?: Array<ApplicationFormDTO>;
  redirectUrl?: string;
}
