/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormContextDTO } from './formContextDTO';
import { Identity } from './identity';

export interface SubmissionContextEnrichedDTO {
  redirectUrl?: string;
  formContexts?: Array<FormContextDTO>;
  similarIdentities?: Array<Identity>;
}
