/**
 * Registrar API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TargetStateConfig {
  state?: TargetStateConfig.StateEnum;
  targetAttribute?: string;
}
export namespace TargetStateConfig {
  export const StateEnum = {
    MEMBER: 'MEMBER',
    NOT_MEMBER: 'NOT_MEMBER',
    FRESH_ATTR_VALUE: 'FRESH_ATTR_VALUE',
  } as const;
  export type StateEnum = (typeof StateEnum)[keyof typeof StateEnum];
}
