/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export var InlineResponse200;
(function (InlineResponse200) {
    InlineResponse200.FormatEnum = {
        DOT: 'DOT',
        TGF: 'TGF'
    };
})(InlineResponse200 || (InlineResponse200 = {}));
//# sourceMappingURL=inlineResponse200.js.map