/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export var InputCreateOwner;
(function (InputCreateOwner) {
    InputCreateOwner.OwnerTypeEnum = {
        NUMBER_0: 0,
        NUMBER_1: 1
    };
})(InputCreateOwner || (InputCreateOwner = {}));
//# sourceMappingURL=inputCreateOwner.js.map