/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export const Type = {
    HTMLCOMMENT: 'HTML_COMMENT',
    SUBMITBUTTON: 'SUBMIT_BUTTON',
    AUTOSUBMITBUTTON: 'AUTO_SUBMIT_BUTTON',
    FROMFEDERATIONSHOW: 'FROM_FEDERATION_SHOW',
    FROMFEDERATIONHIDDEN: 'FROM_FEDERATION_HIDDEN',
    PASSWORD: 'PASSWORD',
    VALIDATEDEMAIL: 'VALIDATED_EMAIL',
    TEXTFIELD: 'TEXTFIELD',
    TEXTAREA: 'TEXTAREA',
    CHECKBOX: 'CHECKBOX',
    RADIO: 'RADIO',
    SELECTIONBOX: 'SELECTIONBOX',
    COMBOBOX: 'COMBOBOX',
    USERNAME: 'USERNAME',
    HEADING: 'HEADING',
    TIMEZONE: 'TIMEZONE'
};
//# sourceMappingURL=type.js.map